id: P003043
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W29900
  title: ཚད་མ་རིགས་པའི་གཏེར་ཞེས་བྱ་བའི་བསྟན་བཅོས།
  author: ''
  volumes:
    c0d9910acece4407a98c37dade57d319:
      image_group_id: I5734
      title: ''
      volume_number: 1
      total_pages: 734
      base_file: v001.txt
